function caseObjects = loadCaseStudies()
% obj.duration = 20.0 / 60;
% obj.durationAfterEstimation = 120.0 / 60.0;
% obj.endEstimation = obj.startTime.shiftedBy(obj.duration * 3600.0);
% obj.endTime = obj.endEstimation.shiftedBy(obj.durationAfterEstimation * 3600.0);
% obj.plotStepTime = 1.0;
% obj.isISL = true;
% obj.islSigma = 0.005;      % filter parameter
% obj.islBaseWeight = 4.0;    % filter parameter
% obj.islSampleTime = 0.10;   % Observation parameter
% obj.islStd = 0.0001;        % Environment parameter
% obj.gpsSampleTime = 1.0;    % Observation parameter
% obj.gpsSigma = 1.8;         % filter parameter
% obj.gpsBaseWeight = 1.0;    % filter parameter
% obj.gpsPositionStd = 100.0; % GPS Position Error ~ 3-sigma: 100 [m]
% obj.gpsVelocitystd = obj.gpsPositionStd / 20; % GPS Velocity Error
% obj.orbitAltitude = 1100000.0;
% obj.orbitInclination = 83.00;
% obj.BLSestimatorConvergenceThreshold = 1e-5;
% obj.BLSestimatorMaxIterations = 25;
%%
numberOfCases = 16;
caseObjects = [];
%% Case 1
caseTemp = ssCOD();
caseTemp.isISL = false;
caseTemp.gpsSampleTime = 0.1;    % Observation parameter
caseTemp.GPSHighRateStep = 1.0 * caseTemp.gpsSampleTime; % step between two consecutive dates within a burst (s)
caseTemp.GPSBurstPeriod  = 1.0 * caseTemp.gpsSampleTime; % period between the start of each burst (s)
caseTemp.gpsPositionStd = 100.0; % GPS Position Error ~ 3-sigma: 100 [m]
caseTemp.gpsVelocitystd = 1.0; % GPS Velocity Error
caseTemp.orbitAltitude = 500000.0;
caseTemp.orbitInclination = 89.83;
import org.orekit.orbits.*;
import org.orekit.utils.*;
caseTemp.referenceOrbit = KeplerianOrbit(Constants.WGS84_EARTH_EQUATORIAL_RADIUS + caseTemp.orbitAltitude, ...
    0.0,  ...
    caseTemp.orbitInclination * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    PositionAngleType.TRUE, ...
    caseTemp.eciFrame, ...
    caseTemp.startTime,  ...
    Constants.WGS84_EARTH_MU);
caseTemp.thisSatellite = [629,17,1,115];
caseObjects = [caseObjects; caseTemp];
%% Case 2
caseTemp = ssCOD();
caseTemp.isISL = false;
caseTemp.gpsSampleTime = 1.0;    % Observation parameter
caseTemp.GPSHighRateStep = 1.0 * caseTemp.gpsSampleTime; % step between two consecutive dates within a burst (s)
caseTemp.GPSBurstPeriod  = 1.0 * caseTemp.gpsSampleTime; % period between the start of each burst (s)
caseTemp.gpsPositionStd = 50.0; % GPS Position Error ~ 3-sigma: 100 [m]
caseTemp.gpsVelocitystd = 0.5; % GPS Velocity Error
caseTemp.orbitAltitude = 500000.0;
caseTemp.orbitInclination = 89.83;
import org.orekit.orbits.*;
import org.orekit.utils.*;
caseTemp.referenceOrbit = KeplerianOrbit(Constants.WGS84_EARTH_EQUATORIAL_RADIUS + caseTemp.orbitAltitude, ...
    0.0,  ...
    caseTemp.orbitInclination * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    PositionAngleType.TRUE, ...
    caseTemp.eciFrame, ...
    caseTemp.startTime,  ...
    Constants.WGS84_EARTH_MU);
caseTemp.thisSatellite = [629,17,1,115];
caseObjects = [caseObjects; caseTemp];
%% Case 3
caseTemp = ssCOD();
caseTemp.isISL = false;
caseTemp.gpsSampleTime = 0.1;    % Observation parameter
caseTemp.GPSHighRateStep = 1.0 * caseTemp.gpsSampleTime; % step between two consecutive dates within a burst (s)
caseTemp.GPSBurstPeriod  = 1.0 * caseTemp.gpsSampleTime; % period between the start of each burst (s)
caseTemp.gpsPositionStd = 100.0; % GPS Position Error ~ 3-sigma: 100 [m]
caseTemp.gpsVelocitystd = 1.0; % GPS Velocity Error
caseTemp.orbitAltitude = 500000.0;
caseTemp.orbitInclination = 89.83;
import org.orekit.orbits.*;
import org.orekit.utils.*;
caseTemp.referenceOrbit = KeplerianOrbit(Constants.WGS84_EARTH_EQUATORIAL_RADIUS + caseTemp.orbitAltitude, ...
    0.0,  ...
    caseTemp.orbitInclination * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    PositionAngleType.TRUE, ...
    caseTemp.eciFrame, ...
    caseTemp.startTime,  ...
    Constants.WGS84_EARTH_MU);
caseTemp.thisSatellite = [629,17,1,115];
caseObjects = [caseObjects; caseTemp];
%% Case 4
caseTemp = ssCOD();
caseTemp.isISL = false;
caseTemp.gpsSampleTime = 0.01;    % Observation parameter
caseTemp.GPSHighRateStep = 1.0 * caseTemp.gpsSampleTime; % step between two consecutive dates within a burst (s)
caseTemp.GPSBurstPeriod  = 1.0 * caseTemp.gpsSampleTime; % period between the start of each burst (s)
caseTemp.gpsPositionStd = 100.0; % GPS Position Error ~ 3-sigma: 100 [m]
caseTemp.gpsVelocitystd = 1.0; % GPS Velocity Error
caseTemp.orbitAltitude = 700000.0;
caseTemp.orbitInclination = 89.00;
import org.orekit.orbits.*;
import org.orekit.utils.*;
caseTemp.referenceOrbit = KeplerianOrbit(Constants.WGS84_EARTH_EQUATORIAL_RADIUS + caseTemp.orbitAltitude, ...
    0.0,  ...
    caseTemp.orbitInclination * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    PositionAngleType.TRUE, ...
    caseTemp.eciFrame, ...
    caseTemp.startTime,  ...
    Constants.WGS84_EARTH_MU);
caseTemp.thisSatellite = [420,15,1,85];
caseObjects = [caseObjects; caseTemp];
%% Case 5
caseTemp = ssCOD();
caseTemp.isISL = false;
caseTemp.gpsSampleTime = 1.0;    % Observation parameter
caseTemp.GPSHighRateStep = 1.0 * caseTemp.gpsSampleTime; % step between two consecutive dates within a burst (s)
caseTemp.GPSBurstPeriod  = 1.0 * caseTemp.gpsSampleTime; % period between the start of each burst (s)
caseTemp.gpsPositionStd = 10.0; % GPS Position Error ~ 3-sigma: 100 [m]
caseTemp.gpsVelocitystd = 0.1; % GPS Velocity Error
caseTemp.orbitAltitude = 1100000.0;
caseTemp.orbitInclination = 83.00;
import org.orekit.orbits.*;
import org.orekit.utils.*;
caseTemp.referenceOrbit = KeplerianOrbit(Constants.WGS84_EARTH_EQUATORIAL_RADIUS + caseTemp.orbitAltitude, ...
    0.0,  ...
    caseTemp.orbitInclination * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    0.0 * (pi / 180),  ...
    PositionAngleType.TRUE, ...
    caseTemp.eciFrame, ...
    caseTemp.startTime,  ...
    Constants.WGS84_EARTH_MU);
caseTemp.thisSatellite = [253,11,1,5];
caseObjects = [caseObjects; caseTemp];

end